### ISSUE TITLE
plotPhenoData - issue with changing size and theme_size

### ISSUE THREAD

**Issue by dat4git** [davismcc/archive-scater#98] opened 2017-02-07 19:27 UTC
Hi,

I am unable to override the default aes parameters in plotPhenoData. For eg, I would like to change the size of the dots in the scatter plot but the following code gives the same results as the default.

plotPhenoData(eset, aes(x = log10_total_counts, y = total_features, size=50))
![image](https://cloud.githubusercontent.com/assets/23667508/22707282/4af42b98-ed40-11e6-869c-25584c30df7c.png)

If I pass the size param to ggplot aes, I still get the default plot in the background
plotPhenoData(eset, aes(x = log10_total_counts, y = total_features)) + geom_point(size=1, color='red')
![image](https://cloud.githubusercontent.com/assets/23667508/22707426/c1c0e324-ed40-11e6-9d6d-3f7dd1e540c8.png)

I took a look at the source code for [plotPhenoData](https://github.com/davismcc/scater/blob/85ec8eb52e98d6188b16ec15de5d089defeee8e5/R/plotting.R) and theoretically it should pass any strings in aes to plotMetadata but I'm not sure why that is not happening. This is true for theme_size as well.

I have attached my session info below. Thanks!
SG

R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggfortify_0.2.0     edgeR_3.14.0        limma_3.28.21       gdata_2.17.0        R.utils_2.5.0      
 [6] R.oo_1.21.0         R.methodsS3_1.7.1   scran_1.0.4         BiocParallel_1.6.6  scater_1.3.35      
[11] ggplot2_2.2.1       Biobase_2.32.0      BiocGenerics_0.18.0

loaded via a namespace (and not attached):
  [1] Rtsne_0.11            ggbeeswarm_0.5.3      minqa_1.2.4           colorspace_1.2-7     
  [5] mvoutlier_2.0.6       rjson_0.2.15          class_7.3-14          modeltools_0.2-21    
  [9] mclust_5.2            dynamicTreeCut_1.63-1 pls_2.5-0             MatrixModels_0.4-1   
 [13] cvTools_0.3.2         affyio_1.42.0         flexmix_2.3-13        AnnotationDbi_1.34.4 
 [17] mvtnorm_1.0-5         splines_3.3.1         sROC_0.1-2            tximport_1.0.3       
 [21] DESeq_1.24.0          robustbase_0.92-6     geneplotter_1.50.0    knitr_1.14           
 [25] nloptr_1.0.4          robCompositions_2.0.2 pbkrtest_0.4-6        annotate_1.50.1      
 [29] cluster_2.0.5         kernlab_0.9-25        vsn_3.40.0            shinydashboard_0.5.3 
 [33] shiny_1.0.0           rrcov_1.4-3           assertthat_0.1        Matrix_1.2-7.1       
 [37] lazyeval_0.2.0        htmltools_0.3.5       quantreg_5.29         tools_3.3.1          
 [41] gtable_0.2.0          affy_1.50.0           reshape2_1.4.2        dplyr_0.5.0          
 [45] Rcpp_0.12.9           trimcluster_0.1-2     sgeostat_1.0-27       preprocessCore_1.34.0
 [49] nlme_3.1-128          fpc_2.1-10            lmtest_0.9-34         laeken_0.4.6         
 [53] stringr_1.1.0         lme4_1.1-12           mime_0.5              gtools_3.5.0         
 [57] XML_3.98-1.4          DEoptimR_1.0-6        zlibbioc_1.18.0       MASS_7.3-45          
 [61] zoo_1.7-13            scales_0.4.1          VIM_4.5.0             BiocInstaller_1.22.3 
 [65] rhdf5_2.16.0          SparseM_1.72          RColorBrewer_1.1-2    gridExtra_2.2.1      
 [69] biomaRt_2.28.0        reshape_0.8.5         stringi_1.1.2         RSQLite_1.0.0        
 [73] highr_0.6             genefilter_1.54.2     S4Vectors_0.10.3      pcaPP_1.9-60         
 [77] e1071_1.6-7           boot_1.3-18           prabclus_2.2-6        matrixStats_0.51.0   
 [81] bitops_1.0-6          lattice_0.20-34       labeling_0.3          GGally_1.2.0         
 [85] plyr_1.8.4            magrittr_1.5          R6_2.2.0              IRanges_2.6.1        
 [89] DBI_0.5-1             mgcv_1.8-15           survival_2.39-5       RCurl_1.95-4.8       
 [93] sp_1.2-3              nnet_7.3-12           tibble_1.2            car_2.1-3            
 [97] viridis_0.3.4         grid_3.3.1            data.table_1.10.0     vcd_1.4-3            
[101] digest_0.6.12         diptest_0.75-7        xtable_1.8-2          tidyr_0.6.0          
[105] httpuv_1.3.3          stats4_3.3.1          munsell_0.4.3         beeswarm_0.2.3       
[109] vipor_0.4.4

**Comment by davismcc** [comment] 2017-02-07 23:37
Thanks for the bug report. I'm swamped at the moment, but will take a closer look at this when I have the chance to do some scater devel again next week. -D.

**Comment by jenzopr** [comment] 2017-02-17 12:23
I was just about to open another issue with the same topic. I would also like it to have a possibility to change the size of the dots.

**Comment by dat4git** [comment] 2017-02-17 21:33
I have a hunch this issue may be related to how aes params are imported into plotMetaData or somewhere upstream of it. For eg. I ran into the same problem when I manually plotted the following:

ggplot(pData(object), aes(total_counts, total_features)) + geom_point(aes(color=is_Col, size=2, alpha=0.5))
![image](https://cloud.githubusercontent.com/assets/23667508/23083825/800b6a7c-f52d-11e6-8dbf-d9a7a0b6ca26.png)

But if we use use brackets around color that allows me to change size etc..
geom_point(aes**(**color=is_Col**)**, size=2, alpha=0.5)
![image](https://cloud.githubusercontent.com/assets/23667508/23084103/c8aac894-f52e-11e6-9f1f-d313d2c64ead.png)

**Comment by davismcc** [comment] 2017-03-27 12:27
Hi both

Thanks for catching these bugs/unexpected behaviour. There was a bug relating to adding the `size` argument, which had the effect of defining the `size` aesthetic as a factor with one level, which was not what should have been done. A similar thing occurred with trying to use the `alpha` argument to `plotMetadata` (and by extension through `...` to `plotPhenoData` and plotFeatureData`). These bugs are fixed in the latest commit, so passing `size`, `alpha` and `shape` arguments to `plotPhenoData` should now work as intended.

There was also a bug with passing the `theme_size` argument to `plotMetadata`. Again this is fixed in the latest commit. 

These bug fixes will be released in the next BIoc release in late April. If you find these functions are still not giving you the expected behaviour, please let me know. 

As you've demonstrated with your examples, it is a challenge to balance convenience and fine-grained aesthetic control over a plot. The `plotPhenoData` function (and likewise `plotFeatureData`) aim for convenience, with the tradeoff that there is less fine-grained control. Hopefully these bug fixes will at least provide the expected and documented behaviour for these functions. For precise control over aesthetics, then it is best to use `ggplot` on `pData(object)`, as the final example usefully shows.

Best
Davis

**Closed as completed by davismcc** 2017-03-27 12:27 UTC
